version: '3.3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: spring-boot-app
    expose: 
      - 8085

  loadbalancer2:
    image: 'dockercloud/haproxy:latest'
    container_name: loadbalancer2  
    links:
      - api
    ports:
      - '8002:8085'      